version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./laravel:/data
      - ./infra/php/php.ini:/usr/local/etc/php/php.ini
      - ./infra/php/log:/var/log

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./laravel:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./db-work:/work
    ports:
      - 33060:3306

  node:
    image: node:lts-alpine
    working_dir: /opt/laravel
    command: [ "npm", "run", "watch-poll" ]
    volumes:
      - npm-cache:/root/.mpm
      - ./laravel:/opt/laravel
    profiles:
      # docker compose up -d では起動しない
      # docker compose --profile extra up -d で起動
      # docker compose --profile extra down で停止
      - extra

volumes:
  db-store:

  npm-cache:
    driver: local
